---

- name: "SSH access | Ensure group developers exists"
  group:
    name: "{{ group_name }}"
    state: present
  tags:
    - add_group
    - grant

- name: "SSH access | Add a new user"
  user:
    name: "{{ user_name }}"
    groups: "{{ group_name }}"
    comment: "{{ user_desc }}"
    password: "{{ user_pass }}"
    shell: /bin/bash
  tags:
    - add_user
    - grant

- name: "SSH access | Add a new user to sudo"
  lineinfile:
    path: "/etc/sudoers.d/{{ user_name }}"
    line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  tags:
    - sudo_user
    - grant


- name: "SSH access | Set includedir in sudoers"
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
  tags:
    - sudo
    - grant


