---

- name: "SSH access | Revoke SSH access"
  user:
    name: "{{ user_name }}"
    state: absent
    remove: yes
  tags:
    - remove_user
    - revoke

- name: "SSH access | Remove a new user to sudo"
  file:
    path: "/etc/sudoers.d/{{ user_name }}"
    state: absent
  tags:
    - remove_user
    - revoke
